[project]
name = "artem-kurs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standart]>=0.116.1",
    "uvicorn>=0.35.0",
]
