"""edit name column in RoomFacilities

Revision ID: b6f53ab4e585
Revises: e566c3abfc39
Create Date: 2025-09-25 18:08:43.313943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6f53ab4e585"
down_revision: Union[str, Sequence[str], None] = "e566c3abfc39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room_facilities", sa.Column("facility_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("room_facilities_faciliti_id_fkey"), "room_facilities", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "room_facilities", "facilities", ["facility_id"], ["id"]
    )
    op.drop_column("room_facilities", "faciliti_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room_facilities",
        sa.Column("faciliti_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "room_facilities", type_="foreignkey")
    op.create_foreign_key(
        op.f("room_facilities_faciliti_id_fkey"),
        "room_facilities",
        "facilities",
        ["faciliti_id"],
        ["id"],
    )
    op.drop_column("room_facilities", "facility_id")
    # ### end Alembic commands ###
